version: "3.9"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./:/app
